### ISSUE TITLE
Authorization header usage not standards compliant

### ISSUE THREAD

**Issue by neilbacon** [data61/anonlink-entity-service#280]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization
Authorization header value must be: `type` `credentials`
and both values are constrained.

I think if we set `type` = "Bearer" then the existing base64 encoded token will be fine as `credentials`.

Aha! Link: https://csiro.aha.io/features/ANONLINK-98

**Comment by gusmith** [comment]
The more I'm thinking about it, the less I think using the Authorization header is a good option:
- the token we are creating is not following any standard authorization protocol (such as OAuth)
- the scheme `bearer` for the header is usually used for OAuth
- if we decide one day to add an authorization solution in the front-end (e.g. access to the whole service, no distinction between endpoints), and it is using the same header, how will we do?
- using a new scheme in the header is possible but we may need to check how to have multiple schemes if required.

Some options:
- creating a new header specific to our application, but it does not seem to be the best way to do as some proxies may filter unknown headers
- using url query parameters instead of the authorization hearder (my preferred way because it will allow us to integrate more easily with any auth solution, does not need configuration of other services)
- just adding the bearer scheme to the current Authorization header despite the mentioned possible issues.

**Comment by gusmith** [comment]
It has been agreed that we won't fix this up to the moment we properly implement authorization.
