### ISSUE TITLE
Migrate default repo from quay.io to dockerhub

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#367]
We've got an org account on docker hub.

https://cloud.docker.com/u/data61/

**Comment by hardbyte** [comment]
Proposed new image names:

- data61/anonlink-app
- data61/anonlink-nginx
- data61/anonlink-benckmark

cc @snayler0

**Comment by gusmith** [comment]
We have now 4 main images:
 - data61/anonlink-app
 - data61/anonlink-nginx
 - data61/anonlink-docs-tutorials -> to test the tutorials
 - data61/anonlink-benchmark -> to run the benchmark
The azure pipeline in the PR #388  and #392 are building and pushing them to dockerhub, using the branch name as tag.

Then there is an extra image data61/anonlink-docs-builder (only tag for the moment is 20190625) which contains the requirements to build the documentation. In fact, the requirement to build the documentation are really long to install, so having this image fasten a lot the creation of the nginx image.

**Comment by hardbyte** [comment]
Cool! If you have any idea how we can decrease the build time for the app or benchmark further with another image please elaborate!

I notice that dockerhub doesn't have the [security scanning feature of quay.io](https://quay.io/repository/n1analytics/entity-app?tab=tags) - so perhaps for now we should keep jenkins pushing to quay.io?

**Comment by gusmith** [comment]
From the PR #388 , Jenkins will not build the entity service anymore, because some changes may/will brake the build on Jenkins, such as using the dockerhub instead of quay.io.
The security scanning feature from quay.io is awesome, and we should check if there are other solution providing the same tools, but relying on dockerhub. I will open an issue about it.
